name: Dataform Format Check

on:
  workflow_dispatch:
  push:
    paths:
      - "**/*.sqlx"
  pull_request:
    paths:
      - "**/*.sqlx"

jobs:
  format-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ci

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "npm"
      - run: npm ci
