name: Dataform Format Check

on:
  workflow_dispatch:

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "npm"
          cache-dependency-path: ./ci/package-lock.json

      - name: Install Dataform CLI
        run: npm install -g @dataform/cli
        working-directory: ./ci

      - name: Run Dataform Format
        run: npx dataform format projectA

      - name: Check for changes after formatting
        id: check-format-changes
        run: |
          if git diff --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Fail CI if formatting changes detected
        if: steps.check-format-changes.outputs.changed == 'true'
        run: |
          echo "Error: Formatting changes were detected. Please run 'dataform format' and commit the changes."
          exit 1
