name: Dataform Format Check

on:
  workflow_dispatch:

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "npm"
          cache-dependency-path: ./ci/package-lock.json

      - name: Install Dataform CLI
        run: npm install -g @dataform/cli
        working-directory: ./ci

      - name: Run Dataform Format
        run: npx dataform format projectA

      - name: Check for modified .sqlx files
        id: check-sqlx-modifications
        run: |
          if git diff --name-only HEAD~1 HEAD | grep -q '\.sqlx$'; then
            echo "modified=true" >> $GITHUB_OUTPUT
          else
            echo "modified=false" >> $GITHUB_OUTPUT
          fi

      - name: Fail CI if .sqlx files are modified
        if: steps.check-sqlx-modifications.outputs.modified == 'true'
        run: |
          echo "Error: .sqlx files have been modified. Please ensure no changes are made."
          exit 1
